name: scube_task_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Regular.ttf
          weight: 400
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/font/Inter-Bold.ttf
          weight: 700
        - asset: assets/font/Inter-Black.ttf
          weight: 900
  #     font:
  #       - asset: font/TrajanPro.ttf
  #       - asset: font/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding font from package dependencies,
  # see https://flutter.dev/to/font-from-package
